name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  neumorphism:
    path: ../../neumorphism
  text_to_path_maker: ^0.5.7
  rxdart: ^0.23.1
  timer_builder: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - asset/
  uses-material-design: true
  fonts:
    - family: PressStart2P
      fonts:
        - asset: third_party/PressStart2P-Regular.ttf
